version: '3'

services:
  master:
    build:
      context: ./master
    ports:
      - "3306:3306"
    networks:
      - mariadb-network

  slave1:
    build:
      context: ./slave1
    ports:
      - "3307:3306"
    networks:
      - mariadb-network
    depends_on:
      - master

  slave2:
    build:
      context: ./slave2
    ports:
      - "3308:3306"
    networks:
      - mariadb-network
    depends_on:
      - master

networks:
  mariadb-network:
    driver: bridge
